### ISSUE TITLE
GafMovieClip does not set child name correctly if multiple children have same name.

### ISSUE THREAD

**Issue by haskasu** [mathieuanthoine/PixiGAFPlayer#1]
in display/GAFMovieClip.hx
```javascript
if(_config.namedParts !=null) {
	var instanceName:String=_config.namedParts[animationObjectConfig.instanceID];
	if (instanceName != null && !Reflect.hasField(this,instanceName)) {
		Reflect.setField(this, _config.namedParts[animationObjectConfig.instanceID], displayObject);
		displayObject.name=instanceName;
	}
}
```
this will only set the first displayObject.name if there are more children with the same name, which is not the same behavior in flash.

Could you make a modification so it works like flashplayer?
something like
```javascript
if(_config.namedParts !=null) {
	var instanceName:String=_config.namedParts[animationObjectConfig.instanceID];
	if (instanceName != null) {
		if(!Reflect.hasField(this,instanceName)) {
			Reflect.setField(this, _config.namedParts[animationObjectConfig.instanceID], displayObject);
		}
		displayObject.name=instanceName;
	}
}
```

I like your gafplayer, saves me a big time!

**Comment by mathieuanthoine** [comment]
Hi @haskasu , do you want to be a part of the project ? It would be easier for you to fix issues and would be for the benefit of the project.
There's a lot of things that need to be implemented in the GAFPlayer but I will be a little bit short in time these next months.

**Comment by mathieuanthoine** [comment]
Please create a Pull request

**Comment by haskasu** [comment]
ok, I will.
sorry , i really want to help, but I don't have the environment to code in haxe (havn't tried).

**Comment by mathieuanthoine** [comment]
If you need it quickly it's the best solution :)
Install haxe and FlashDevelop and you'll be ready. Don't hesitate if you have problems to configured you environment.
