### ISSUE TITLE
HaxePixiGAF: GAF compressed format not supported yet

### ISSUE THREAD

**Issue by pautus** [mathieuanthoine/PixiGAFPlayer#3]
Hello,

Trying to implement an animation from Animate CC but  having that issue in console. Is there a way to fix it when exporting ?

Thanks

**Comment by mathieuanthoine** [comment]
Hi,

If you want to use the PixiGAFPlayer you need to use uncompressed files. check the requirements of Pixi GAF Library and configure your GAF Converter : https://github.com/mathieuanthoine/PixiGAFPlayer
